name: CI
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  ci_main_release:
    name: Industrial CI against release repository
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  ci_testing_release:
    name: Industrial CI against testing repository
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  ci_source:
    name: ros-tooling CI from source
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-ci@0.0.19
        with:
          target-ros2-distro: foxy
          package-name:  |
            ros2_tutorial
            action_example
            intra_process_example
            launch_example
            lifecycle_example
            param_example
            service_example
            topic_example
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ros_ws/lcov/total_coverage.info
      #     flags: unittests
      #     name: codecov-umbrella
      #     yml: ./codecov.yml
      #     fail_ci_if_error: true
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
