# https://github.com/ros-tooling/action-ros-lint#usage

name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic  # To be updated to focal
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, uncrustify, flake8, mypy, pep257, pep8, xmllint]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          package-name: |
            ros2_tutorial_cpp
            topic_example
            service_example
            action_example
            param_example
            interface_example
            intra_process_example
            launch_example
            lifecycle_example
            plugin_example
            rqt_example
