# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ament_lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, uncrustify, pep8, pep257, xmllint]
        distribution: [foxy]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: ${{ matrix.distribution }}
          linter: ${{ matrix.linter }}
          package-name: |
            ros2_tutorial
            action_example
            interface_example
            intra_process_example
            launch_example
            lifecycle_example
            param_example
            plugin_example
            rqt_example
            service_example
            topic_example
