# https://github.com/ros-tooling/action-ros-lint#usage
# https://github.com/ros-controls/ros2_control/blob/master/.github/workflows/lint.yml

name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ament_lint:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, uncrustify, flake8, pep257, xmllint]
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name: |
            ros2_tutorial_cpp
            topic_tutorial_cpp
            service_tutorial_cpp
